---
title: "Dalla Fork alla Pull Request"
author: "Elia Vangi"
date: "31 marzo 2018"
output: html_document
     
         
---
##Accenno su GitHub

GitHub è una piattaforma *hostin web* basata sul software *open source* di *version control*Git, che permette lo sviluppo in collaborazione di progetti di qualunque tipo.
Una volta aperto un account su GitHub, sarà possibile caricare progetti e lavori da condividere con gli altri utenti;cercare nelle *repository* di altri alla ricerca di un progetto interessante con il quale collaborare o dal quale prendere spunto; entrare in contatto con altre persone e condividere con loro progetti e idee

##Repository

Una *Repository* (abbreviata in repo) è il "luogo" dove viene caricato un progetto. Contiene tutti i file inerenti al progetto e tutte le versioni dello stesso. Nel caso di repo pubbliche le repo possono essere visibili a tutti, gli utenti possono accedervi e modificare il progetto. Per evitare che chiunque possa manomettere o scombinare i codici, i cambiamenti apportati al progetto devono essere valutati e concessi dall'autore della repo.

##Fork

una *Fork* è una copia di una repo e permette di compiere qualunque modifica senza agire sul progetto originale.Più comunemente, le *Fork* vengono utilizzate per proporre modifiche al progetto di qualcun altro o per utilizzare il progetto di qualcun altro come punto di partenza per la propria idea.

##Pull Request

Una volta apportate le modifiche nella tua *Fork* potresti voler chiedere all'autore del progetto originale di inserire le tue modifiche nella repo originale. Questa richiesta prende il nome di *Pull Request*.Una volta aperta una *Pull Request*, è possibile discutere e rivedere le potenziali modifiche con i collaboratori prima che le modifiche vengano unite nella *Repository*.

###Come creare una Fork